package mcp

// These exercise the path policy the proxied tools apply, which is the whole
// reason they exist: the sandbox bounds the session to the worktree, and a
// committed .env, a generated file and every path the task never declared are
// all inside the worktree.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/akynte/local-engineer/internal/firewall"
)

func editRepo(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	write := func(rel, body string) {
		full := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o750); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	write("risk/order.go", "package risk\n\nfunc Check() error {\n\treturn nil\n}\n")
	write(".env", "AWS_SECRET_ACCESS_KEY=real\n")
	write("api/events.pb.go", "// Code generated by protoc. DO NOT EDIT.\npackage api\n")
	return root
}

// The access check is what both proxied tools call, so this pins the decisions
// they inherit rather than re-deriving them through the MCP plumbing.
func TestProxiedReadRefusesSecretPathsInsideTheWorktree(t *testing.T) {
	root := editRepo(t)
	access := firewall.Access{}

	if err := access.Check(root, ".env", false); err == nil {
		t.Fatal("a committed .env was readable through the proxied path policy")
	}
	if err := access.Check(root, "risk/order.go", false); err != nil {
		t.Fatalf("ordinary source was refused: %v", err)
	}
}

func TestProxiedWriteIsBoundedByTheDeclaredScope(t *testing.T) {
	root := editRepo(t)

	// The scope the task declared is the whole authority for a write.
	scoped := firewall.Access{WriteScope: []string{"risk/order.go"}}
	if err := scoped.Check(root, "risk/order.go", true); err != nil {
		t.Fatalf("a declared file was refused: %v", err)
	}
	err := scoped.Check(root, "risk/pnl.go", true)
	if err == nil {
		t.Fatal("a write outside the declared scope was allowed")
	}
	if !strings.Contains(err.Error(), "re-plan") {
		t.Fatalf("the refusal does not say what to do instead: %v", err)
	}

	// An empty scope is no authority at all, which is what a session that
	// never declared one gets.
	if err := (firewall.Access{}).Check(root, "risk/order.go", true); err == nil {
		t.Fatal("a session that declared no scope could still write")
	}

	// Generated output is refused even when the scope names it: the generator
	// owns that file and the next run would discard the edit.
	generated := firewall.Access{WriteScope: []string{"api/events.pb.go"}}
	err = generated.Check(root, "api/events.pb.go", true)
	if err == nil {
		t.Fatal("generated output was hand-editable")
	}
	if !strings.Contains(err.Error(), "regenerate") {
		t.Fatalf("the refusal does not name the alternative: %v", err)
	}
}

// Replacing text that appears twice would change a line the model never read,
// and text that appears zero times means it is working from a version of the
// file that no longer exists.
func TestExactlyOnceIsTheEditContract(t *testing.T) {
	body := "a := 1\nb := 2\na := 1\n"
	if got := strings.Count(body, "a := 1"); got != 2 {
		t.Fatalf("fixture is wrong: %d", got)
	}
	if got := strings.Count(body, "b := 2"); got != 1 {
		t.Fatalf("fixture is wrong: %d", got)
	}
	if got := strings.Count(body, "c := 3"); got != 0 {
		t.Fatalf("fixture is wrong: %d", got)
	}
	// strings.Replace with n=1 is what the tool uses, and it must leave the
	// second occurrence alone.
	out := strings.Replace(body, "b := 2", "b := 3", 1)
	if strings.Count(out, "a := 1") != 2 {
		t.Fatal("a single replacement disturbed another line")
	}
}
