#!/usr/bin/env bash
# Generate docs/reference/image-manifest.md from an image (design v3 §4.2:
# "every tool version listed in docs/reference/image-manifest.md generated at
# build time").
#
# It is generated rather than written because a hand-maintained list of tool
# versions is wrong the first time anything is bumped, and wrong in the
# direction that matters: it claims a version the image does not have.
#
#   scripts/image-manifest.sh local-engineer:cpu-test > docs/reference/image-manifest.md
set -euo pipefail

image="${1:?usage: image-manifest.sh <image>}"

# Ask the image itself. Anything else is a second source of truth.
run() { docker run --rm --entrypoint sh "$ref" -c "$1" 2>/dev/null || true; }

version_of() {
  local bin="$1" cmd="$2"
  local out
  out="$(run "command -v $bin >/dev/null 2>&1 && $cmd")"
  out="$(printf '%s' "$out" | head -1 | tr -d '\r')"
  if [ -z "$out" ]; then
    printf 'not present'
  else
    printf '%s' "$out"
  fi
}

# Resolve the tag to an id first. Some image stores (Docker Desktop's
# containerd backend) will inspect by id but not by tag, and a script that
# assumed otherwise would emit an empty manifest rather than fail loudly.
ref="$(docker images --format '{{.Repository}}:{{.Tag}}\t{{.ID}}' \
        | awk -v want="$image" -F'\t' '$1 == want {print $2; exit}')"
if [ -z "$ref" ]; then
  echo "image-manifest: no image named $image" >&2
  exit 1
fi

inspect() { docker image inspect --format "$1" "$ref" 2>/dev/null; }

digest="$(inspect '{{if .RepoDigests}}{{index .RepoDigests 0}}{{end}}')"
[ -z "$digest" ] && digest='(not pushed; no digest)'
imageID="$(inspect '{{.Id}}')"
created="$(inspect '{{.Created}}')"
size="$(inspect '{{.Size}}' | awk '{printf "%.0f MB", $1/1048576}')"

cat <<HEADER
# Image manifest

Every tool in the image, with the version the image actually has.

**Generated by \`scripts/image-manifest.sh\`, not written by hand.** A
hand-maintained list is wrong the first time anything is bumped, and wrong in
the direction that matters: it claims a version the image does not have, which
is exactly the claim someone reads it to check.

## Image

| | |
|---|---|
| Reference | \`$image\` |
| Digest | \`$digest\` |
| Image ID | \`$imageID\` |
| Created | $created |
| Size | $size |

Pin by digest, not by tag. A tag moves; the digest is the thing you tested.

## Base

\`\`\`
$(run 'cat /etc/os-release 2>/dev/null | grep -E "^(PRETTY_NAME|VERSION_ID)=" | head -2')
\`\`\`

## Tools

| Tool | Version |
|---|---|
HEADER

while IFS='|' read -r bin cmd; do
  [ -z "$bin" ] && continue
  printf '| `%s` | %s |\n' "$bin" "$(version_of "$bin" "$cmd")"
done <<'TOOLS'
le|le version --short 2>/dev/null || le version
go|go version
node|node --version
llama-server|llama-server --version 2>&1 | head -1
git|git --version
rg|rg --version | head -1
gopls|gopls version | head -1
staticcheck|staticcheck -version
golangci-lint|golangci-lint --version | head -1
govulncheck|govulncheck -version 2>&1 | head -1
gosec|gosec -version 2>&1 | head -1
semgrep|semgrep --version
gitleaks|gitleaks version
osv-scanner|osv-scanner --version 2>&1 | head -1
trivy|trivy --version | head -1
buf|buf --version
benchstat|benchstat -h 2>&1 | head -1
bwrap|bwrap --version
TOOLS

cat <<'FOOTER'

## Reading this

`not present` is a fact about the variant, not a gap. The `-slim` image carries
the supervisor and no toolchain; the `-cpu` image carries no CUDA runtime. §4.2
describes three variants on purpose, and a tool missing from one is why you
would choose another.

Regenerate after any change to `deploy/Dockerfile`:

```console
$ scripts/image-manifest.sh ghcr.io/akynte/local-engineer:<version> \
    > docs/reference/image-manifest.md
```
FOOTER
