#!/usr/bin/env bash
# Generate docs/reference/image-manifest.md from an image (design v3 §4.2:
# "every tool version listed in docs/reference/image-manifest.md generated at
# build time").
#
# It is generated rather than written because a hand-maintained list of tool
# versions is wrong the first time anything is bumped, and wrong in the
# direction that matters: it claims a version the image does not have.
#
#   scripts/image-manifest.sh local-engineer:cpu-test > docs/reference/image-manifest.md
set -euo pipefail

image="${1:?usage: image-manifest.sh <image>}"

# Ask the image itself. Anything else is a second source of truth.
run() { docker run --rm --entrypoint sh "$ref" -c "$1" 2>/dev/null || true; }

version_of() {
  local bin="$1" cmd="$2"
  local out
  out="$(run "command -v $bin >/dev/null 2>&1 && $cmd")"
  out="$(printf '%s' "$out" | head -1 | tr -d '\r')"
  if [ -z "$out" ]; then
    printf 'not present'
  else
    printf '%s' "$out"
  fi
}

# Resolve the tag to an id first. Some image stores (Docker Desktop's
# containerd backend) will inspect by id but not by tag, and a script that
# assumed otherwise would emit an empty manifest rather than fail loudly.
ref="$(docker images --format '{{.Repository}}:{{.Tag}}\t{{.ID}}' \
        | awk -v want="$image" -F'\t' '$1 == want {print $2; exit}')"
if [ -z "$ref" ]; then
  echo "image-manifest: no image named $image" >&2
  exit 1
fi

inspect() { docker image inspect --format "$1" "$ref" 2>/dev/null; }

digest="$(inspect '{{if .RepoDigests}}{{index .RepoDigests 0}}{{end}}')"
[ -z "$digest" ] && digest='(not pushed; no digest)'
imageID="$(inspect '{{.Id}}')"
created="$(inspect '{{.Created}}')"
size="$(inspect '{{.Size}}' | awk '{printf "%.0f MB", $1/1048576}')"

cat <<HEADER
# Image manifest

Every tool in the image, with the version the image actually has.

**Generated by \`scripts/image-manifest.sh\`, not written by hand.** A
hand-maintained list is wrong the first time anything is bumped, and wrong in
the direction that matters: it claims a version the image does not have, which
is exactly the claim someone reads it to check.

## Image

| | |
|---|---|
| Reference | \`$image\` |
| Digest | \`$digest\` |
| Image ID | \`$imageID\` |
| Created | $created |
| Size | $size |

Pin by digest, not by tag. A tag moves; the digest is the thing you tested.

## Base

\`\`\`
$(run 'cat /etc/os-release 2>/dev/null | grep -E "^(PRETTY_NAME|VERSION_ID)=" | head -2')
\`\`\`

## Tools

| Tool | Version |
|---|---|
HEADER

while IFS='|' read -r bin cmd; do
  [ -z "$bin" ] && continue
  printf '| `%s` | %s |\n' "$bin" "$(version_of "$bin" "$cmd")"
done <<'TOOLS'
le|le version --short 2>/dev/null || le version
go|go version
node|node --version
llama-server|llama-server --version 2>&1 | head -1
git|git --version
rg|rg --version | head -1
gopls|gopls version | head -1
staticcheck|staticcheck -version
golangci-lint|golangci-lint --version | head -1
govulncheck|govulncheck -version 2>&1 | head -1
gosec|gosec -version 2>&1 | head -1
semgrep|semgrep --version
gitleaks|gitleaks version
osv-scanner|osv-scanner --version 2>&1 | head -1
trivy|trivy --version | head -1
buf|buf --version
squawk|squawk --version
oasdiff|oasdiff --version 2>&1 | head -1
benchstat|benchstat -h 2>&1 | head -1
bwrap|bwrap --version
TOOLS

# The TypeScript sidecar is not a binary on PATH, so it needs its own probe.
# It is listed because §3.2's TypeScript rows are `resolved` only when it is
# installed: an image without it analyses TypeScript lexically and emits no
# call graph, which is a property of the image someone reads this table to
# check.
sidecar_dir='/opt/le/sidecars/typescript'
sidecar="$(run "test -f $sidecar_dir/analyze.js && node -p \"'typescript ' + require('$sidecar_dir/node_modules/typescript/package.json').version\"")"
sidecar="$(printf '%s' "$sidecar" | head -1 | tr -d '\r')"
printf '| `typescript-sidecar` | %s |\n' "${sidecar:-not present}"

cat <<'FOOTER'

## Reading this

`not present` is a fact about the variant, not a gap. The `-slim` image carries
the supervisor and no toolchain; the `-cpu` image carries no CUDA runtime. §4.2
describes three variants on purpose, and a tool missing from one is why you
would choose another.

### What is here, and why

**The engine has no shell tool.** Its only route to an external program is
`run_recipe`, so a binary that no recipe invokes cannot be reached by a task at
all — it would be bytes with no capability. That is the rule for what belongs
in this image.

Two tools have built-in recipes:

| Tool | Recipe |
|---|---|
| `golangci-lint` | the `lint` kind, where the repository committed a `.golangci.yml` |
| `semgrep` | the `analyzer` kind, where the repository carries rules under `semgrep/` |

The rest are reached through a `check:` step in `.le/verify.yaml`, because
which tables a migration may lock, and which proto changes are breaking, are
facts about a repository rather than about Go. See
[declare runtime and generation checks](../how-to/declare-runtime-checks.md).

| §4.2 tool | Why it is absent |
|---|---|
| Playwright browsers | No image ships a UI for a browser to drive, so 300 MB of browsers would run nothing. An `integration:` step is how you use one if you install it yourself. [Verify item 5](verify-list.md) tracks whether they belong in their own layer. |
| `trivy` | It reports vulnerabilities in dependencies, so a task would fail for a CVE published between two runs — a property of the world, not of the change. That belongs in CI, where it is, not in a completion contract. Declare it as a `check:` step and install it if you disagree. |
| OpenCode | Superseded by [DR-7](../adr/0007-native-engine.md): the engine is native and does not need it. |

Regenerate after any change to `deploy/Dockerfile`:

```console
$ scripts/image-manifest.sh ghcr.io/akynte/local-engineer:<version> \
    > docs/reference/image-manifest.md
```
FOOTER
